### ISSUE TITLE
No publishable resources for tag [woocommerce-template-views]

### ISSUE THREAD

**Issue by jarimbi** [generoi/sage-woocommerce#21]
After wp acorn vendor:publish --tag="woocommerce-template-views" 
INFO  No publishable resources for tag [woocommerce-template-views]
is returned an no files are being copied.
Sage 10.6

**Comment by jarimbi** [comment]
Same for wp acorn vendor:publish --tag="woocommerce-template-hooks"

**Comment by zhyvotovskiy** [comment]
Try those command
`wp acorn vendor:publish --tag="WooCommerce Templates"`
and
`wp acorn vendor:publish --tag="WooCommerce Template Hook Overrides"`

**Comment by jarimbi** [comment]
That works. Thanks!

**Comment by oxyc** [comment]
Sorry the README shown here on github was for the master branch which still wasn't tagged as a release. I just released v1.1.1 which will include the changed tag names
