### ISSUE TITLE
Custom Taxonomy templates not working.

### ISSUE THREAD

**Issue by mrogaar** [generoi/sage-woocommerce#27]
Hi,

I'm trying to create a template of a custom taxonomy 'brand' linked to woocommerce's 'product' post_type. However when I try to make my template (taxonomy-brand.blade.php) it wont show me the template, it inherits the default archive-product.blade.php template.

**Comment by oxyc** [comment]
Works for me but this isnt sage-woocommerce related. If you register a custom taxonomy the template should be in `views/taxonomy-<slug>.blade.php` like all other taxonomies.

I'll close this task but feel free to comment if there's something else. Roots Discourse might be better to get support though.
