### ISSUE TITLE
Package not fully loaded?

### ISSUE THREAD

**Issue by gizburdt** [generoi/sage-woocommerce#30]
Hi,

Again, awesome package!

I'm using Radicle. WooCommerce thinks the theme is not supporting WooCommerce. When looking at WooCommerce > Status > Theme, it says "WooCommerce support: Not declared"

When digging further, putting a dd() in `namespace Genero\Sage\WooCommerce\WooCommerce::addThemeSupport`, there is no dump, so it looks like this function in not called from the WooCommerceServiceProvider. Putting a dd() in the ServiceProvider itself will dump.

I also published the views, and changing them won't do anything.

I followed all steps from the installation guide. I hope I'm not forgetting something and wasting your time. Hope you can help me. :)

**Comment by oxyc** [comment]
Hmm strange, I cannot reproduce although I do not have access to Radicle and not sure what their setup looks like. Maybe it runs `\Roots\bootloader()->boot();` runs earlier than regular bedrock+sage.

But so for you it's https://github.com/generoi/sage-woocommerce/blob/master/src/WooCommerceServiceProvider.php#L26 which doesnt evaluate to true and  thus skips?

Which acorn version are you using?
Could you show `d(debug_backtrace());?

**Comment by gizburdt** [comment]
This one returns true: https://github.com/generoi/sage-woocommerce/blob/master/src/WooCommerceServiceProvider.php#L26

Dumping in bindFilters will also be called, but dumping in all methods called within bindFilters wont do anything.

I included the backtrace

[trace.txt](https://github.com/generoi/sage-woocommerce/files/14417367/trace.txt)

**Comment by gizburdt** [comment]
Did you maybe have some time to look at this issue? :)

**Comment by oxyc** [comment]
I did but couldn’t see anything that stands out. Unfortunately I don’t have radicle so cant verify but I do think others use both together without issues.

I would debug by:
1. Check error logs
2. Verify that this variable gets the correct object: https://github.com/generoi/sage-woocommerce/blob/master/src/WooCommerceServiceProvider.php#L43
3. Try adding         add_action('after_setup_theme', fn() => d('test')); next to the one that doesn’t run

Looks like the bootstrap happens in a mu-plugin and while I haven’t tested that I cant see why it wouldn’t work.

**Comment by oxyc** [comment]
Could also try changing the resolving of the woocommerce object to:

$woocommerce= $this->app->make(WooCommerce::class);

**Comment by gizburdt** [comment]
Thanks!

1. Empty
2. Dumping `$woocommerce` gives `Genero\Sage\WooCommerce\WooCommerce`
3. Not dumping anything, even tried to put it directly in the `boot` method

**Comment by oxyc** [comment]
Does it work in your theme? or maybe use error_log() instead of d().

**Comment by oxyc** [comment]
Which version of acorn do you have? Do you have 4.0.2 or older?

**Comment by gizburdt** [comment]
Acorn is v4.0.3

**Comment by oxyc** [comment]
Unfortunately I can’t really help. At this point I wouldn’t trust d() and instead use error_log() or xdebug.

**Comment by gizburdt** [comment]
I understand :) Thanks for the help!

You are mentioned as the go to package on the Roots website when using WooCommerce. Maybe you can ask them for a Radicle license, so you can make it compatible with Radicle.

For now, I'm switching back to Bedrock + Sage.

**Comment by oxyc** [comment]
Thanks! Could you test if the following works and I can create a patch release fixing it

```php
    public function bindSetupAction(): void
    {
        if (doing_action('after_setup_theme')) {
            $this->app['woocommerce']->addThemeSupport();
        } else {
            add_action('after_setup_theme', [$this->app['woocommerce'], 'addThemeSupport']);
        }
    }
```

**Comment by johanmolen** [comment]
@oxyc that works 🙌

**Comment by oxyc** [comment]
Thanks! I published a new release
