### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by visualasparagus** [generoi/sage-woocommerce#34]
In the documentation it says to run `wp acorn package:discover` but for me I needed to run `wp @development acorn package:discover`. Also for the remaining wp calls. This may be because I'm using Lima on OSX but thought it was worth mentioning.

**Comment by oxyc** [comment]
That’s a wp cli alias and depends on your environment so I think it’s more suitable for Lima to document that all wp cli calls should use the alias. But thanks anyway
